### ISSUE TITLE
What next?

### ISSUE THREAD

**Issue by MereutaRadu** [azzogat/FiiPractic#2]
What is left to be done till next week? I'll try and arrange the code in the Scene file so it will look better. Other than that...what is left to be done ? 

(Since i left early i may have missed some stuff)

Btw: Are the code changes done Sunday gonna be committed?

**Comment by tudor07** [comment]
Trebuia sa facem componentele unui obiect (transform, controller, texture, mesh etc)

**Comment by cuvidk** [comment]
Ideea e ca in final (pana duminica) ar trebui sa avem o forma geometrica mai complexa (un cub). Pe care il poti controla prin keyboard.

Answer to your question "Btw question" : If yes, we would have nothing to do...So I guess no
