### ISSUE TITLE
gutrunks why did you change the controller?

### ISSUE THREAD

**Issue by MereutaRadu** [azzogat/FiiPractic#4]
Why did you change the controller and removed the Z position correction an rotation implementation? O.o

**Comment by gutrunks** [comment]
I changed nothing on the controller. Just added glut, camera component and a ton shader (that needs some tweaking and is completely commented) touched nothing else anywhere. Not even a call to what I did.

**Comment by gutrunks** [comment]
And regarding the z position, I used it for the camera, why would I change in in the controller. Anyway, I'm sorry if it happened from my commit, but it shouldn't have.

**Comment by MereutaRadu** [comment]
No probs :) i'll recommit after i see what happened there :) you probably haven't updated my last commit and that's why it they got erased :)

**Comment by gutrunks** [comment]
More that likely. Sorry again. Just mentioned I made no changes to those so you don't try to look for anything extra. Thanks again for the heads up.

**Comment by MereutaRadu** [comment]
Psst...could you recommit? apparently the component camera file and the tronshader.cpp one are not found by visual. And i can't find them either in the components folder... :)

**Comment by gutrunks** [comment]
Will do... But I'm not at my computer right now. But I'll do it when I can and I'll be sure to not mess it up this time

**Comment by MereutaRadu** [comment]
also: glut32.lib is missing...be sure to upload that as well :P
