### ISSUE TITLE
assimp/linking problems

### ISSUE THREAD

**Issue by narcis2007** [azzogat/FiiPractic#5]
there is a problem in ComponentMesh.h:
when i build i have this error: Error	5	error C1083: Cannot open include file: 'assimp\Importer.hpp': No such file or directory
when i replace #include <assimp\Importer.hpp>
#include <assimp\scene.h> with #include <../assimp-3.1.1/include/assimp/Importer.hpp>
#include <../assimp-3.1.1/include/assimp/scene.h> i get linking errors
...does anyone knows how to fix this?

**Comment by HidiPaul** [comment]
link the assimp library

**Comment by HidiPaul** [comment]
also add
$(SolutionDir)/externals/assimp-3.1.1/include/Compiler
into the Library directions for the VC++ Directories in project properties
Also
$(SolutionDir)/externals/assimp-3.1.1/include
into the Include Directories, same place

**Comment by HidiPaul** [comment]
Also did u pull the assimp folder from the externals directory?

**Comment by narcis2007** [comment]
did that, got rid of the initial error and only got 3 linking errors, after
i put $(SolutionDir)/externals/assimp-3.1.1/lib32/assimp.lib in
linker/additional dependencies i got a lot more linking errors
and yes i have the assimp folder in the externals directory

i haven't liked it properly or there is other problem?

2015-05-08 17:44 GMT+03:00 HidiPaul <notifications@github.com>:

> Also did u pull the assimp folder from the externals directory?
>
>
> On Fri, May 8, 2015 at 4:42 PM, Paul-Daniel Hidi <hidi.paul@gmail.com>
>
> wrote:
>
> > also add
> > $(SolutionDir)/externals/assimp-3.1.1/include/Compiler
> > into the Library directions for the VC++ Directories in project
> properties
> > Also
> > $(SolutionDir)/externals/assimp-3.1.1/include
> > into the Include Directories, same place
> >
> > On Fri, May 8, 2015 at 4:38 PM, Paul-Daniel Hidi <hidi.paul@gmail.com>
> > wrote:
> >
> >> link the assimp library
> >>
> >>
> >> On Fri, May 8, 2015 at 3:52 PM, Ciobotariu Narcis <

**Comment by tudor07** [comment]
Didn't the teacher say we have to rebuild assimp for Visual Studio 2013 ?

**Comment by HidiPaul** [comment]
Dont worry, I nearly reinvented assimp to make it work.
Try adding
$(SolutionDir)/externals/assimp-3.1.1/include
in the C/C++->General->Additional Include Directories
Also, you should have
assimp.lib
in Linker->Input->Additional Dependencies

You also need to have assimpd.dll in the build/Debug folder if it says that
it cannot find assimp.exe

ALSO, try linking assimp.lib(the one in the lib folder), I think its
different from the one in the lib32/lib64 one, I had to rebuild the
library(several times...) to make it work.

**Comment by tudor07** [comment]
It works now... 
But there are some errors with a null pointer in scene.h from assimp/

**Comment by HidiPaul** [comment]
Impressive......an error even I didn't get.
